version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: scooter_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: scooter_rent
      TZ: Europe/Kyiv
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: