spring.application.name=demo

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/scooter_rent
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

nagement.endpoint.health.show-details=always

management.endpoints.web.exposure.include=health, metrics, prometheus

